version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/" # root
    schedule:
      interval: "weekly" # 
      day: "monday"       # 
      time: "08:00"       # UTC
    open-pull-requests-limit: 10
    versioning-strategy: increase
    commit-message:
      prefix: "chore"
      include: "scope"
    labels:
      - "dependencies"
    assignees:
      - "yukiakai212" #

