name: Release and Publish

on:
  push:
    branches:
      - main

jobs:
  release:
    if: startsWith(github.event.head_commit.message, 'release:')
    name: Publish to npm
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write  

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: 'https://registry.npmjs.org/'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci
      - name: Parse publish tag from Git tag
        uses: yukiakai212/publish-tag@v1
        id: tag
        with:
          source: 'package.json'
      - name: Authenticate with NPM TOKEN
        run: npm config set //registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}
      - name: Build package
        run: npm run test
      - name: Publish to npm with provenance
        run: npm publish --provenance --access public --tag ${{ steps.tag.outputs.tag }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
